name: Erblint style checks

on:
  pull_request:
    paths: ['app/**/*.erb']

jobs:
  erblint:
    name: Erblint
    runs-on: ${{ github.repository_owner == 'CMSgov' && format('codebuild-emmy-github-runner-emmy-app-{0}-{1}', github.run_id, github.run_attempt) || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Javascript
        uses: ./.github/actions/setup-languages
      - name: Run Erblint
        working-directory: app
        run: bundle exec erb_lint --lint-all
